FROM python:3.9-slim

WORKDIR /app

RUN pip install flask opentelemetry-api opentelemetry-sdk \
    opentelemetry-exporter-otlp-proto-grpc \
    opentelemetry-instrumentation-flask \
    opentelemetry-instrumentation-requests \
    prometheus-client requests

COPY sample-app.py .

EXPOSE 8080

CMD ["python", "sample-app.py"]
